onboarding = false

[theme]
name = "tokyo-night"

[keys]
prefix = "ctrl+space"

previous_tab = ["prefix+p", "ctrl+left"]
next_tab = ["prefix+n", "ctrl+right"]

focus_pane_left = ["prefix+h", "prefix+left", "ctrl+alt+h"]
focus_pane_down = ["prefix+j", "prefix+down", "ctrl+alt+j"]
focus_pane_up = ["prefix+k", "prefix+up", "ctrl+alt+k"]
focus_pane_right = ["prefix+l", "prefix+right", "ctrl+alt+l"]

next_agent = "prefix+a"
previous_agent = "prefix+shift+a"

split_vertical = "prefix+v"
split_horizontal = ["prefix+s", "prefix+minus"]
settings = "prefix+comma"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "lazygit"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+alt+y"
type = "popup"
command = "yazi"
description = "yazi"
width = "90%"
height = "90%"

[ui]
prompt_new_tab_name = false

[ui.toast]
delivery = "herdr"
