format = """
 \
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$python\
$cmd_duration\
$line_break\
$character\
"""

[python]
format = ' [()(\($virtualenv\)) ](#c0caf5)'

[directory]
style = "#7aa2f7"

[git_branch]
format = "[](#c0caf5) [$branch](#4fd6be)"

[cmd_duration]
format = "[ took](#c0caf5) [$duration](#ffc777)"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
