format = """
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$line_break\
$character\
"""

[python]
format = '[()(\($virtualenv\)) ](#ffffff)' 
style = ""

[username]
format = "[$user](#35a79c bold) "
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](#3da4ab bold) '
trim_at = "."
disabled = false

[directory]
format = "at [$path]($style)[$read_only]($read_only_style) "
read_only = " "
truncation_length = 10
truncate_to_repo = true
style = "#f6cd61 bold"

[git_branch]
symbol = ""
style = "#fe8a71"
